{"body": "The original patch failed because it removed the `list()` cast around the fetch, which meant that the `try`, which was detecting if the database wasn't available at all, wasn't catching the connection error, since the recipes were now being fetched lazily. Adding the `list()` cast back in fixes this.\r\n\r\nSince this PR went up, we disabled the checks in question due to #900, so nothing is running these checks anyway, including the tests. You can test this issue locally by un-commenting the lines in `normandy.recipes.checks.register` that disabled the checks, and running `./manage.py check` with Normandy pointing at an uninitialized database.", "body_text": "The original patch failed because it removed the list() cast around the fetch, which meant that the try, which was detecting if the database wasn't available at all, wasn't catching the connection error, since the recipes were now being fetched lazily. Adding the list() cast back in fixes this.\nSince this PR went up, we disabled the checks in question due to #900, so nothing is running these checks anyway, including the tests. You can test this issue locally by un-commenting the lines in normandy.recipes.checks.register that disabled the checks, and running ./manage.py check with Normandy pointing at an uninitialized database.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/323214714", "created_at": "2017-08-17T22:47:58Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/893#issuecomment-323214714", "updated_at": "2017-08-17T22:47:58Z", "user": {"following_url": "https://api.github.com/users/Osmose/following{/other_user}", "events_url": "https://api.github.com/users/Osmose/events{/privacy}", "organizations_url": "https://api.github.com/users/Osmose/orgs", "url": "https://api.github.com/users/Osmose", "gists_url": "https://api.github.com/users/Osmose/gists{/gist_id}", "html_url": "https://github.com/Osmose", "subscriptions_url": "https://api.github.com/users/Osmose/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/193106?v=4", "repos_url": "https://api.github.com/users/Osmose/repos", "received_events_url": "https://api.github.com/users/Osmose/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/Osmose/starred{/owner}{/repo}", "site_admin": false, "login": "Osmose", "type": "User", "id": 193106, "followers_url": "https://api.github.com/users/Osmose/followers"}, "body_html": "<p>The original patch failed because it removed the <code>list()</code> cast around the fetch, which meant that the <code>try</code>, which was detecting if the database wasn't available at all, wasn't catching the connection error, since the recipes were now being fetched lazily. Adding the <code>list()</code> cast back in fixes this.</p>\n<p>Since this PR went up, we disabled the checks in question due to <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"244498588\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/mozilla/normandy/issues/900\" href=\"https://github.com/mozilla/normandy/issues/900\">#900</a>, so nothing is running these checks anyway, including the tests. You can test this issue locally by un-commenting the lines in <code>normandy.recipes.checks.register</code> that disabled the checks, and running <code>./manage.py check</code> with Normandy pointing at an uninitialized database.</p>", "id": 323214714, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/893"}