{"body": "Taskcluster failed with issue from #757 again, despite the robustcheckout fix. The log shows robustcheckout resuming after each \"file not found\" error, making more progress each time. It didn't finish before the 3rd error though, and the default number of retries is 3.", "body_text": "Taskcluster failed with issue from #757 again, despite the robustcheckout fix. The log shows robustcheckout resuming after each \"file not found\" error, making more progress each time. It didn't finish before the 3rd error though, and the default number of retries is 3.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/305932678", "created_at": "2017-06-02T23:41:54Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/791#issuecomment-305932678", "updated_at": "2017-06-02T23:41:54Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>Taskcluster failed with issue from <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"228179592\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/mozilla/normandy/issues/757\" href=\"https://github.com/mozilla/normandy/issues/757\">#757</a> again, despite the robustcheckout fix. The log shows robustcheckout resuming after each \"file not found\" error, making more progress each time. It didn't finish before the 3rd error though, and the default number of retries is 3.</p>", "id": 305932678, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/791"}