{"body": "With this patch, the `/classify/` view gives me this:\n\n```\nTraceback (most recent call last):\n  File \"/home/mythmon/src/normandy/venv/lib/python3.5/site-packages/django/core/handlers/base.py\", line 149, in get_response\n    response = self.process_exception_by_middleware(e, request)\n  File \"/home/mythmon/src/normandy/venv/lib/python3.5/site-packages/django/core/handlers/base.py\", line 147, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/mythmon/src/normandy/normandy/classifier/views.py\", line 15, in classify\n    return HttpResponseRedirect(BundlerView.url_for(bundle))\n  File \"/home/mythmon/src/normandy/normandy/bundler/views.py\", line 29, in url_for\n    return urlparams(reverse('normandy.bundler'), hash=bundle.hash, ids=bundle.ids)\n  File \"/home/mythmon/src/normandy/normandy/bundler/models.py\", line 17, in hash\n    recipe_hashes = '_'.join([recipe.content_hash for recipe in self.recipes])\n  File \"/home/mythmon/src/normandy/normandy/bundler/models.py\", line 17, in <listcomp>\n    recipe_hashes = '_'.join([recipe.content_hash for recipe in self.recipes])\nAttributeError: 'Recipe' object has no attribute 'content_hash'\n```\n", "body_text": "With this patch, the /classify/ view gives me this:\nTraceback (most recent call last):\n  File \"/home/mythmon/src/normandy/venv/lib/python3.5/site-packages/django/core/handlers/base.py\", line 149, in get_response\n    response = self.process_exception_by_middleware(e, request)\n  File \"/home/mythmon/src/normandy/venv/lib/python3.5/site-packages/django/core/handlers/base.py\", line 147, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/mythmon/src/normandy/normandy/classifier/views.py\", line 15, in classify\n    return HttpResponseRedirect(BundlerView.url_for(bundle))\n  File \"/home/mythmon/src/normandy/normandy/bundler/views.py\", line 29, in url_for\n    return urlparams(reverse('normandy.bundler'), hash=bundle.hash, ids=bundle.ids)\n  File \"/home/mythmon/src/normandy/normandy/bundler/models.py\", line 17, in hash\n    recipe_hashes = '_'.join([recipe.content_hash for recipe in self.recipes])\n  File \"/home/mythmon/src/normandy/normandy/bundler/models.py\", line 17, in <listcomp>\n    recipe_hashes = '_'.join([recipe.content_hash for recipe in self.recipes])\nAttributeError: 'Recipe' object has no attribute 'content_hash'", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/171380521", "created_at": "2016-01-13T17:59:44Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/3#issuecomment-171380521", "updated_at": "2016-01-13T17:59:44Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>With this patch, the <code>/classify/</code> view gives me this:</p>\n<pre><code>Traceback (most recent call last):\n  File \"/home/mythmon/src/normandy/venv/lib/python3.5/site-packages/django/core/handlers/base.py\", line 149, in get_response\n    response = self.process_exception_by_middleware(e, request)\n  File \"/home/mythmon/src/normandy/venv/lib/python3.5/site-packages/django/core/handlers/base.py\", line 147, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"/home/mythmon/src/normandy/normandy/classifier/views.py\", line 15, in classify\n    return HttpResponseRedirect(BundlerView.url_for(bundle))\n  File \"/home/mythmon/src/normandy/normandy/bundler/views.py\", line 29, in url_for\n    return urlparams(reverse('normandy.bundler'), hash=bundle.hash, ids=bundle.ids)\n  File \"/home/mythmon/src/normandy/normandy/bundler/models.py\", line 17, in hash\n    recipe_hashes = '_'.join([recipe.content_hash for recipe in self.recipes])\n  File \"/home/mythmon/src/normandy/normandy/bundler/models.py\", line 17, in &lt;listcomp&gt;\n    recipe_hashes = '_'.join([recipe.content_hash for recipe in self.recipes])\nAttributeError: 'Recipe' object has no attribute 'content_hash'\n</code></pre>", "id": 171380521, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/3"}