{"original_position": 5, "diff_hunk": "@@ -101,9 +101,15 @@ def test_it_cant_edit_actions_in_use(self, api_client, settings):\n \n         res = api_client.patch('/api/v1/action/active/', {'implementation': 'foobar'})\n         assert res.status_code == 403\n+        assert res.data == {\n+            'detail': 'Cannot edit this object while it is in use'", "body_text": "I want to assert that the right kind of error got thrown. I want to make sure this is an \"object in use\" error, and not an \"admin disabled\" error. We could also this with something like assert res.data['detail'] == NotInUse.message, if changing error strings ends up being annoying.", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/35", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/53084533", "created_at": "2016-02-16T21:47:52Z", "author_association": "MEMBER", "body": "I want to assert that the right kind of error got thrown. I want to make sure this is an \"object in use\" error, and not an \"admin disabled\" error. We could also this with something like `assert res.data['detail'] == NotInUse.message`, if changing error strings ends up being annoying.\n", "updated_at": "2016-02-16T21:47:52Z", "html_url": "https://github.com/mozilla/normandy/pull/35#discussion_r53084533", "pull_request_review_id": null, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/53084533"}, "html": {"href": "https://github.com/mozilla/normandy/pull/35#discussion_r53084533"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/35"}}, "commit_id": "e5aeb5e27a3d8ce4061e3b92698aa8a2dde0d07d", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "position": 5, "path": "normandy/recipes/tests/test_api.py", "body_html": "<p>I want to assert that the right kind of error got thrown. I want to make sure this is an \"object in use\" error, and not an \"admin disabled\" error. We could also this with something like <code>assert res.data['detail'] == NotInUse.message</code>, if changing error strings ends up being annoying.</p>", "original_commit_id": "e5aeb5e27a3d8ce4061e3b92698aa8a2dde0d07d", "id": 53084533}