{"body": "Yeah, this was the error caused by Python 3.6 + new versions of eventlet.", "body_text": "Yeah, this was the error caused by Python 3.6 + new versions of eventlet.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/283248141", "created_at": "2017-03-01T05:24:10Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/issues/522#issuecomment-283248141", "updated_at": "2017-03-01T05:24:10Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>Yeah, this was the error caused by Python 3.6 + new versions of eventlet.</p>", "id": 283248141, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/522"}