{"original_position": 19, "diff_hunk": "@@ -0,0 +1,30 @@\n+import { BASE_API_URL, API_REQUEST_SETTINGS } from '../constants.js';\n+import { showNotification } from './ControlActions.js';\n+\n+export const AUTH_TOKEN_REQUEST_IN_PROGRESS = 'AUTH_TOKEN_REQUEST';\n+export const AUTH_TOKEN_REQUEST_COMPLETE = 'AUTH_TOKEN_REQUEST_SUCCESS';\n+\n+\n+export function requestAPIToken() {\n+  return async dispatch => {\n+    dispatch({ type: AUTH_TOKEN_REQUEST_IN_PROGRESS });\n+    const response = await fetch(`${BASE_API_URL}token/`, API_REQUEST_SETTINGS);\n+\n+    if (response.status >= 400) {\n+      dispatch({\n+        type: AUTH_TOKEN_REQUEST_COMPLETE,\n+        status: 'error',\n+      });\n+      dispatch(showNotification('Error fetching API token'));\n+      throw await response.json();", "body_text": "This is interesting - I have not seen anyone just throw a JSON object on errors like this, but it makes sense!", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/355", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/89152420", "created_at": "2016-11-22T16:20:37Z", "author_association": "CONTRIBUTOR", "body": "This is interesting - I have not seen anyone just throw a JSON object on errors like this, but it makes sense!", "updated_at": "2016-11-28T23:11:34Z", "html_url": "https://github.com/mozilla/normandy/pull/355#discussion_r89152420", "pull_request_review_id": 9700598, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/89152420"}, "html": {"href": "https://github.com/mozilla/normandy/pull/355#discussion_r89152420"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/355"}}, "commit_id": "e74e606a9115a24d47bceecf665f4503a3c011e1", "user": {"following_url": "https://api.github.com/users/andymikulski/following{/other_user}", "events_url": "https://api.github.com/users/andymikulski/events{/privacy}", "organizations_url": "https://api.github.com/users/andymikulski/orgs", "url": "https://api.github.com/users/andymikulski", "gists_url": "https://api.github.com/users/andymikulski/gists{/gist_id}", "html_url": "https://github.com/andymikulski", "subscriptions_url": "https://api.github.com/users/andymikulski/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/2767162?v=4", "repos_url": "https://api.github.com/users/andymikulski/repos", "received_events_url": "https://api.github.com/users/andymikulski/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/andymikulski/starred{/owner}{/repo}", "site_admin": false, "login": "andymikulski", "type": "User", "id": 2767162, "followers_url": "https://api.github.com/users/andymikulski/followers"}, "position": null, "path": "client/control/actions/authActions.js", "body_html": "<p>This is interesting - I have not seen anyone just throw a JSON object on errors like this, but it makes sense!</p>", "original_commit_id": "f775d1eca79ef165d350a74ad2aa9fd2a5a35e47", "id": 89152420}