{"original_position": 19, "diff_hunk": "@@ -0,0 +1,30 @@\n+import { BASE_API_URL, API_REQUEST_SETTINGS } from '../constants.js';\n+import { showNotification } from './ControlActions.js';\n+\n+export const AUTH_TOKEN_REQUEST_IN_PROGRESS = 'AUTH_TOKEN_REQUEST';\n+export const AUTH_TOKEN_REQUEST_COMPLETE = 'AUTH_TOKEN_REQUEST_SUCCESS';\n+\n+\n+export function requestAPIToken() {\n+  return async dispatch => {\n+    dispatch({ type: AUTH_TOKEN_REQUEST_IN_PROGRESS });\n+    const response = await fetch(`${BASE_API_URL}token/`, API_REQUEST_SETTINGS);\n+\n+    if (response.status >= 400) {\n+      dispatch({\n+        type: AUTH_TOKEN_REQUEST_COMPLETE,\n+        status: 'error',\n+      });\n+      dispatch(showNotification('Error fetching API token'));\n+      throw await response.json();", "body_text": "Oh. hmm. I think throwing a non-Error object like this might actually be bad. At one point we had a lint against it (but I guess not anymore).", "in_reply_to_id": 89152420, "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/355", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/89219890", "created_at": "2016-11-22T22:02:20Z", "author_association": "MEMBER", "body": "Oh. hmm. I think throwing a non-Error object like this might actually be bad. At one point we had a lint against it (but I guess not anymore).", "updated_at": "2016-11-28T23:11:34Z", "html_url": "https://github.com/mozilla/normandy/pull/355#discussion_r89219890", "pull_request_review_id": 9766759, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/89219890"}, "html": {"href": "https://github.com/mozilla/normandy/pull/355#discussion_r89219890"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/355"}}, "commit_id": "e74e606a9115a24d47bceecf665f4503a3c011e1", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "position": null, "path": "client/control/actions/authActions.js", "body_html": "<p>Oh. hmm. I think throwing a non-Error object like this might actually be bad. At one point we had a lint against it (but I guess not anymore).</p>", "original_commit_id": "f775d1eca79ef165d350a74ad2aa9fd2a5a35e47", "id": 89219890}