{"original_position": 20, "diff_hunk": "@@ -1,13 +1,34 @@\n import { Action, registerAction } from '../utils';\n \n export default class ShieldStudyAction extends Action {\n-  constructor(normandy, recipe) {\n-    super(normandy, recipe);\n-    this.storage = normandy.createStorage(recipe.id);\n+  setHasBeenShown() {\n+    this.storage.setItem('studyHasBeenShown', true);\n+  }\n+\n+  async getHasBeenShown() {\n+    const hasBeenShown = await this.storage.getItem('studyHasBeenShown');\n+    return hasBeenShown;\n   }\n \n   async execute() {\n+    try {\n+      this.storage = await this.normandy.createStorage(this.recipe.id);\n+    } catch (error) {\n+      throw new Error(error);", "body_text": "You don't need to catch and then rethrow the error. You can just let it fail, leaving out all the try/catch stuff.", "pull_request_url": "https://api.github.com/repos/mozilla/normandy/pulls/291", "url": "https://api.github.com/repos/mozilla/normandy/pulls/comments/83105964", "created_at": "2016-10-12T21:46:57Z", "author_association": "MEMBER", "body": "You don't need to catch and then rethrow the error. You can just let it fail, leaving out all the try/catch stuff.\n", "updated_at": "2016-11-03T23:10:01Z", "html_url": "https://github.com/mozilla/normandy/pull/291#discussion_r83105964", "pull_request_review_id": 3969074, "_links": {"self": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/comments/83105964"}, "html": {"href": "https://github.com/mozilla/normandy/pull/291#discussion_r83105964"}, "pull_request": {"href": "https://api.github.com/repos/mozilla/normandy/pulls/291"}}, "commit_id": "f905b2547d3135fff8e4e9a69edcfae9c9892a91", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "position": null, "path": "client/actions/shield-study/index.js", "body_html": "<p>You don't need to catch and then rethrow the error. You can just let it fail, leaving out all the try/catch stuff.</p>", "original_commit_id": "82266f2030c81ce6cb804a638f516d60a3aa08bd", "id": 83105964}