{"body": "@mythmon Any idea as to why Taskcluster is failing on this? Locally, the addon tests pass fine, and looking at (what I think are) the logs, I don't really see any errors indicating the problem.", "body_text": "@mythmon Any idea as to why Taskcluster is failing on this? Locally, the addon tests pass fine, and looking at (what I think are) the logs, I don't really see any errors indicating the problem.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/290464197", "created_at": "2017-03-30T16:23:26Z", "author_association": "CONTRIBUTOR", "html_url": "https://github.com/mozilla/normandy/pull/633#issuecomment-290464197", "updated_at": "2017-03-30T16:23:37Z", "user": {"following_url": "https://api.github.com/users/andymikulski/following{/other_user}", "events_url": "https://api.github.com/users/andymikulski/events{/privacy}", "organizations_url": "https://api.github.com/users/andymikulski/orgs", "url": "https://api.github.com/users/andymikulski", "gists_url": "https://api.github.com/users/andymikulski/gists{/gist_id}", "html_url": "https://github.com/andymikulski", "subscriptions_url": "https://api.github.com/users/andymikulski/subscriptions", "avatar_url": "https://avatars1.githubusercontent.com/u/2767162?v=4", "repos_url": "https://api.github.com/users/andymikulski/repos", "received_events_url": "https://api.github.com/users/andymikulski/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/andymikulski/starred{/owner}{/repo}", "site_admin": false, "login": "andymikulski", "type": "User", "id": 2767162, "followers_url": "https://api.github.com/users/andymikulski/followers"}, "body_html": "<p><a class=\"user-mention\" href=\"https://github.com/mythmon\">@mythmon</a> Any idea as to why Taskcluster is failing on this? Locally, the addon tests pass fine, and looking at (what I think are) the logs, I don't really see any errors indicating the problem.</p>", "id": 290464197, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/633"}