{"body": "This is failing because #59 added `./manage.py check` to CI, and the database isn't set up at that time.\n\nOn the one hand, running the checks might find some silly errors with models, so could be good to run in CI. On the other hand, I don't know how to fix this, so I wonder if removing the `check` from CI is reasonable.\n", "body_text": "This is failing because #59 added ./manage.py check to CI, and the database isn't set up at that time.\nOn the one hand, running the checks might find some silly errors with models, so could be good to run in CI. On the other hand, I don't know how to fix this, so I wonder if removing the check from CI is reasonable.", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/191524482", "created_at": "2016-03-03T01:17:55Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/61#issuecomment-191524482", "updated_at": "2016-03-03T01:17:55Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<p>This is failing because <a class=\"issue-link js-issue-link\" data-error-text=\"Failed to load issue title\" data-id=\"137992010\" data-permission-text=\"Issue title is private\" data-url=\"https://github.com/mozilla/normandy/issues/59\" href=\"https://github.com/mozilla/normandy/pull/59\">#59</a> added <code>./manage.py check</code> to CI, and the database isn't set up at that time.</p>\n<p>On the one hand, running the checks might find some silly errors with models, so could be good to run in CI. On the other hand, I don't know how to fix this, so I wonder if removing the <code>check</code> from CI is reasonable.</p>", "id": 191524482, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/61"}