{"body": "> Before I forget, I suspect our current webpack_loader will not fly when we upgrade to Django 2\r\n\r\nLuckily, by the time we switch to Django 2, we won't need to have any webpack loaders or any client JS at all. So that's great.\r\n\r\nIf all the tests and CI pass, and there aren't explosive errors from a basic click through of the site, I'm happy to approve this. We have pretty good automated tests and sort of ok automatic verification of, and the UI is almost entirely JS anyways.\r\n\r\nThat being said, there was a problem in the dependencies step of the CI. It is related to the mock-server, which is going away. It may represent a problem in the update though. Can you look into it?\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"./manage.py\", line 11, in <module>\r\n    execute_from_command_line(sys.argv)\r\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\r\n    utility.execute()\r\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 356, in execute\r\n    self.fetch_command(subcommand).run_from_argv(self.argv)\r\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 206, in fetch_command\r\n    klass = load_command_class(app_name, subcommand)\r\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 40, in load_command_class\r\n    module = import_module('%s.management.commands.%s' % (app_name, name))\r\n  File \"/usr/local/lib/python3.6/importlib/__init__.py\", line 126, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 978, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 961, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 950, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 655, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\r\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\r\n  File \"/app/normandy/recipes/management/commands/initial_data.py\", line 2, in <module>\r\n    from django_countries import countries\r\n  File \"/usr/local/lib/python3.6/site-packages/django_countries/__init__.py\", line 5, in <module>\r\n    from django_countries.conf import settings\r\n  File \"/usr/local/lib/python3.6/site-packages/django_countries/conf.py\", line 4, in <module>\r\n    class AppSettings(django.conf.BaseSettings):\r\n\r\nAttributeError: module 'django.conf' has no attribute 'BaseSettings'\r\n```", "body_text": "Before I forget, I suspect our current webpack_loader will not fly when we upgrade to Django 2\n\nLuckily, by the time we switch to Django 2, we won't need to have any webpack loaders or any client JS at all. So that's great.\nIf all the tests and CI pass, and there aren't explosive errors from a basic click through of the site, I'm happy to approve this. We have pretty good automated tests and sort of ok automatic verification of, and the UI is almost entirely JS anyways.\nThat being said, there was a problem in the dependencies step of the CI. It is related to the mock-server, which is going away. It may represent a problem in the update though. Can you look into it?\nTraceback (most recent call last):\n  File \"./manage.py\", line 11, in <module>\n    execute_from_command_line(sys.argv)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 206, in fetch_command\n    klass = load_command_class(app_name, subcommand)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 40, in load_command_class\n    module = import_module('%s.management.commands.%s' % (app_name, name))\n  File \"/usr/local/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"<frozen importlib._bootstrap>\", line 978, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 961, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 950, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 655, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 678, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 205, in _call_with_frames_removed\n  File \"/app/normandy/recipes/management/commands/initial_data.py\", line 2, in <module>\n    from django_countries import countries\n  File \"/usr/local/lib/python3.6/site-packages/django_countries/__init__.py\", line 5, in <module>\n    from django_countries.conf import settings\n  File \"/usr/local/lib/python3.6/site-packages/django_countries/conf.py\", line 4, in <module>\n    class AppSettings(django.conf.BaseSettings):\n\nAttributeError: module 'django.conf' has no attribute 'BaseSettings'", "url": "https://api.github.com/repos/mozilla/normandy/issues/comments/371289679", "created_at": "2018-03-07T21:24:10Z", "author_association": "MEMBER", "html_url": "https://github.com/mozilla/normandy/pull/1204#issuecomment-371289679", "updated_at": "2018-03-07T21:24:10Z", "user": {"following_url": "https://api.github.com/users/mythmon/following{/other_user}", "events_url": "https://api.github.com/users/mythmon/events{/privacy}", "organizations_url": "https://api.github.com/users/mythmon/orgs", "url": "https://api.github.com/users/mythmon", "gists_url": "https://api.github.com/users/mythmon/gists{/gist_id}", "html_url": "https://github.com/mythmon", "subscriptions_url": "https://api.github.com/users/mythmon/subscriptions", "avatar_url": "https://avatars3.githubusercontent.com/u/305049?v=4", "repos_url": "https://api.github.com/users/mythmon/repos", "received_events_url": "https://api.github.com/users/mythmon/received_events", "gravatar_id": "", "starred_url": "https://api.github.com/users/mythmon/starred{/owner}{/repo}", "site_admin": false, "login": "mythmon", "type": "User", "id": 305049, "followers_url": "https://api.github.com/users/mythmon/followers"}, "body_html": "<blockquote>\n<p>Before I forget, I suspect our current webpack_loader will not fly when we upgrade to Django 2</p>\n</blockquote>\n<p>Luckily, by the time we switch to Django 2, we won't need to have any webpack loaders or any client JS at all. So that's great.</p>\n<p>If all the tests and CI pass, and there aren't explosive errors from a basic click through of the site, I'm happy to approve this. We have pretty good automated tests and sort of ok automatic verification of, and the UI is almost entirely JS anyways.</p>\n<p>That being said, there was a problem in the dependencies step of the CI. It is related to the mock-server, which is going away. It may represent a problem in the update though. Can you look into it?</p>\n<pre><code>Traceback (most recent call last):\n  File \"./manage.py\", line 11, in &lt;module&gt;\n    execute_from_command_line(sys.argv)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 364, in execute_from_command_line\n    utility.execute()\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 356, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 206, in fetch_command\n    klass = load_command_class(app_name, subcommand)\n  File \"/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py\", line 40, in load_command_class\n    module = import_module('%s.management.commands.%s' % (app_name, name))\n  File \"/usr/local/lib/python3.6/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 978, in _gcd_import\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 961, in _find_and_load\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 950, in _find_and_load_unlocked\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 655, in _load_unlocked\n  File \"&lt;frozen importlib._bootstrap_external&gt;\", line 678, in exec_module\n  File \"&lt;frozen importlib._bootstrap&gt;\", line 205, in _call_with_frames_removed\n  File \"/app/normandy/recipes/management/commands/initial_data.py\", line 2, in &lt;module&gt;\n    from django_countries import countries\n  File \"/usr/local/lib/python3.6/site-packages/django_countries/__init__.py\", line 5, in &lt;module&gt;\n    from django_countries.conf import settings\n  File \"/usr/local/lib/python3.6/site-packages/django_countries/conf.py\", line 4, in &lt;module&gt;\n    class AppSettings(django.conf.BaseSettings):\n\nAttributeError: module 'django.conf' has no attribute 'BaseSettings'\n</code></pre>", "id": 371289679, "issue_url": "https://api.github.com/repos/mozilla/normandy/issues/1204"}